"""drop old unique email index

Revision ID: 1d93786a3ef2
Revises: 9fff892668cc
Create Date: 2026-02-19 23:40:44.300351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d93786a3ef2'
down_revision = '9fff892668cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
