"""Increase password hash length

Revision ID: 85987076a10d
Revises: 9473ffb72cca
Create Date: 2026-02-16 22:49:35.586202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85987076a10d'
down_revision = '9473ffb72cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
