"""remove unique from name fields

Revision ID: 8aa1ff8b881f
Revises: 
Create Date: 2026-02-08 01:24:50.574754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa1ff8b881f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('users_first_name_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_last_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_last_name_key'), ['last_name'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_first_name_key'), ['first_name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
