"""add partial unique index for email

Revision ID: 9fff892668cc
Revises: 85987076a10d
Create Date: 2026-02-19 23:01:34.230096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fff892668cc'
down_revision = '85987076a10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'CREATE UNIQUE INDEX uq_user_email ON users (email) WHERE btrim(email) <> \'\''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_email', table_name='users')
    # ### end Alembic commands ###