"""remove unique=True staff user in inactive_user

Revision ID: ce39bd111994
Revises: d6479ca87c9f
Create Date: 2026-03-31 11:14:29.173897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce39bd111994'
down_revision = 'd6479ca87c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inactive_users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('inactive_users_staff_username_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inactive_users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('inactive_users_staff_username_key'), ['staff_username'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
