"""add InactiveUser table

Revision ID: d6479ca87c9f
Revises: 1d93786a3ef2
Create Date: 2026-03-05 10:57:17.831200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6479ca87c9f'
down_revision = '1d93786a3ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inactive_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deactivated_on', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('active_role', sa.String(length=64), nullable=False),
    sa.Column('inactive_role', sa.String(length=64), nullable=False),
    sa.Column('staff_username', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_username')
    )
    with op.batch_alter_table('inactive_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inactive_users_username'), ['username'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_user_email'), postgresql_where="(btrim((email)::text) <> ''::text)")
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('uq_user_email'), ['email'], unique=True, postgresql_where="(btrim((email)::text) <> ''::text)")

    with op.batch_alter_table('inactive_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inactive_users_username'))

    op.drop_table('inactive_users')
    # ### end Alembic commands ###
